name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: macos-latest

    env:
      FLUTTER_CHANNEL: stable
      FLUTTER_VERSION: 3.22.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - name: Install dependencies
      working-directory: example
      run: flutter pub get

    - name: Build Android
      working-directory: example
      run: flutter build apk --release

    - name: Publish dry-run
      run: dart pub publish --dry-run

    - name: Build iOS
      working-directory: example
      run: git submodule sync --recursive && git submodule update --init --recursive && flutter build ios --release --no-codesign